name              'sensors'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures sensor polling using lm-sensors or openipmi on Linux systems'
version           '2.0.9'
source_url        'https://github.com/sous-chefs/sensors'
issues_url        'https://github.com/sous-chefs/sensors/issues'
chef_version      '>= 15.5'

supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
