name              'sensors'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures sensor polling using lm-sensors or openipmi on Linux systems'
version           '3.0.0'
source_url        'https://github.com/sous-chefs/sensors'
issues_url        'https://github.com/sous-chefs/sensors/issues'
chef_version      '>= 15.5'

supports 'almalinux', '>= 8.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
